$codes = {
  '3000' => { :code => '3000', :type => 'Apple', :variety => 'Alkmene' },
  '3001' => { :code => '3001', :type => 'Apple', :variety => 'Aurora / Southern Rose, small' },
  '3002' => { :code => '3002', :type => 'Apple', :variety => 'Cantared' },
  '3003' => { :code => '3003', :type => 'Apple', :variety => 'D\'Estivale' },
  '3004' => { :code => '3004', :type => 'Apple', :variety => 'Discovery' },
  '3005' => { :code => '3005', :type => 'Apple', :variety => 'Golden Delicious Blush' },
  '3006' => { :code => '3006', :type => 'Apple', :variety => 'Ingrid Marie' },
  '3007' => { :code => '3007', :type => 'Apple', :variety => 'Lochbuie' },
  '3008' => { :code => '3008', :type => 'Apple', :variety => 'Rubinette' },
  '3009' => { :code => '3009', :type => 'Apple', :variety => 'Russet' },
  '3011' => { :code => '3011', :type => 'Apple', :variety => 'Worcester' },
  '3012' => { :code => '3012', :type => 'Pear', :variety => 'Abate Fetel' },
  '3013' => { :code => '3013', :type => 'Pear', :variety => 'Beurre Hardy' },
  '3014' => { :code => '3014', :type => 'Pear', :variety => 'Bon Rouge' },
  '3015' => { :code => '3015', :type => 'Pear', :variety => 'Clara Friis' },
  '3016' => { :code => '3016', :type => 'Pear', :variety => 'Concorde' },
  '3017' => { :code => '3017', :type => 'Pear', :variety => 'Conference' },
  '3018' => { :code => '3018', :type => 'Pear', :variety => 'Durondeau' },
  '3019' => { :code => '3019', :type => 'Pear', :variety => 'Flamingo' },
  '3020' => { :code => '3020', :type => 'Pear', :variety => 'General Leclerc' },
  '3021' => { :code => '3021', :type => 'Pear', :variety => 'Guyot' },
  '3022' => { :code => '3022', :type => 'Pear', :variety => 'Josephine' },
  '3024' => { :code => '3024', :type => 'Pear', :variety => 'Rocha' },
  '3025' => { :code => '3025', :type => 'Pear', :variety => 'Rosemarie' },
  '3026' => { :code => '3026', :type => 'Pear', :variety => 'Triumph de Vienne' },
  '3027' => { :code => '3027', :type => 'Orange', :variety => 'Shamouti' },
  '3030' => { :code => '3030', :type => 'Tangerine / Mandarin', :variety => 'Nova' },
  '3031' => { :code => '3031', :type => 'Tangerine / Mandarin', :variety => 'Jamaican Tangor' },
  '3037' => { :code => '3037', :type => 'Pineapple', :variety => 'Queen' },
  '3038' => { :code => '3038', :type => 'Passion Fruit', :variety => 'Granadilla / Grenadilla Orange' },
  '3039' => { :code => '3039', :type => 'Berries', :variety => 'Gooseberry / Ground Cherry / Physalis / Cape' },
  '3041' => { :code => '3041', :type => 'Rambutan', :variety => '' },
  '3042' => { :code => '3042', :type => 'Mangosteen', :variety => '' },
  '3043' => { :code => '3043', :type => 'Grape', :variety => 'Italian, seeded' },
  '3046' => { :code => '3046', :type => 'Date', :variety => 'Fresh / Frozen' },
  '3047' => { :code => '3047', :type => 'Date', :variety => 'Medjool' },
  '3048' => { :code => '3048', :type => 'Bean', :variety => 'Helda / Flat' },
  '3049' => { :code => '3049', :type => 'Bean', :variety => 'Fine' },
  '3050' => { :code => '3050', :type => 'Cabbage', :variety => 'Dutch White / Winter White' },
  '3051' => { :code => '3051', :type => 'Cabbage', :variety => 'Spring Cabbage / Spring Greens' },
  '3052' => { :code => '3052', :type => 'Garlic', :variety => 'String' },
  '3053' => { :code => '3053', :type => 'Parsnip', :variety => 'Baby' },
  '3059' => { :code => '3059', :type => 'Squash', :variety => 'Crown Prince' },
  '3060' => { :code => '3060', :type => 'Squash', :variety => 'Vegetable Marrow' },
  '3061' => { :code => '3061', :type => 'Tomato', :variety => 'Beef / Beefsteak' },
  '3062' => { :code => '3062', :type => 'Herbs', :variety => 'Bay Leaves' },
  '3063' => { :code => '3063', :type => 'Herbs', :variety => 'Fennel Leaves' },
  '3064' => { :code => '3064', :type => 'Herbs', :variety => 'Aloe Vera Leaves' },
  '3072' => { :code => '3072', :type => 'Apple', :variety => 'Lady' },
  '3073' => { :code => '3073', :type => 'Apple', :variety => 'Macoun' },
  '3074' => { :code => '3074', :type => 'Apple', :variety => 'Greening / Rhode Island' },
  '3075' => { :code => '3075', :type => 'Apple', :variety => 'Baldwin' },
  '3076' => { :code => '3076', :type => 'Apple', :variety => 'Melrose' },
  '3077' => { :code => '3077', :type => 'Apple', :variety => 'Northern Spy' },
  '3078' => { :code => '3078', :type => 'Apple', :variety => 'Liberty' },
  '3080' => { :code => '3080', :type => 'Avocado', :variety => 'Pinkerton' },
  '3081' => { :code => '3081', :type => 'Berries', :variety => 'Saskatoons' },
  '3082' => { :code => '3082', :type => 'Broccoli', :variety => 'Crowns' },
  '3083' => { :code => '3083', :type => 'Brussels Sprout', :variety => 'Stalk' },
  '3084' => { :code => '3084', :type => 'Herbs', :variety => 'Chervil' },
  '3088' => { :code => '3088', :type => 'Currant', :variety => 'Red' },
  '3089' => { :code => '3089', :type => 'Eggplant', :variety => 'Chinese' },
  '3090' => { :code => '3090', :type => 'Eggplant', :variety => 'Thai' },
  '3091' => { :code => '3091', :type => 'Gobo Root', :variety => 'Gobo Root / Burdock Root' },
  '3092' => { :code => '3092', :type => 'Grapefruit', :variety => 'Blanco / Sweetie' },
  '3099' => { :code => '3099', :type => 'Lotus Root', :variety => '' },
  '3100' => { :code => '3100', :type => 'Melon', :variety => 'Gold Honeydew' },
  '3101' => { :code => '3101', :type => 'Melon', :variety => 'Piel de Sapo' },
  '3102' => { :code => '3102', :type => 'Mushroom', :variety => 'Morel' },
  '3103' => { :code => '3103', :type => 'Mushroom', :variety => 'Enoki' },
  '3105' => { :code => '3105', :type => 'Nuts', :variety => 'Cashews' },
  '3106' => { :code => '3106', :type => 'Nuts', :variety => 'Macadamia' },
  '3109' => { :code => '3109', :type => 'Orange', :variety => 'Seville / Marmalade type' },
  '3111' => { :code => '3111', :type => 'Papaya / Pawpaw', :variety => 'Red-Fleshed / Solo Sunrise' },
  '3112' => { :code => '3112', :type => 'Papaya / Pawpaw', :variety => 'Meridol' },
  '3113' => { :code => '3113', :type => 'Peach', :variety => 'Donut / Flat Chinese' },
  '3118' => { :code => '3118', :type => 'Pear', :variety => 'Starkrimson' },
  '3125' => { :code => '3125', :type => 'Pepper', :variety => 'Habanero' },
  '3126' => { :code => '3126', :type => 'Plumcot', :variety => '' },
  '3130' => { :code => '3130', :type => 'Pumpkin', :variety => 'Jumbo' },
  '3131' => { :code => '3131', :type => 'Pumpkin', :variety => 'Decorative / Painted' },
  '3132' => { :code => '3132', :type => 'Pumpkin', :variety => 'White' },
  '3134' => { :code => '3134', :type => 'Pumpkin', :variety => 'Pie Pumpkin' },
  '3135' => { :code => '3135', :type => 'Pumpkin', :variety => 'Ornamental' },
  '3136' => { :code => '3136', :type => 'Sapote', :variety => 'Sapodillo / Nispero' },
  '3139' => { :code => '3139', :type => 'Herbs', :variety => 'Savory' },
  '3140' => { :code => '3140', :type => 'Squash', :variety => 'Cucuzza' },
  '3141' => { :code => '3141', :type => 'Squash', :variety => 'Opo' },
  '3142' => { :code => '3142', :type => 'Squash', :variety => 'Carnival' },
  '3144' => { :code => '3144', :type => 'Tangerine / Mandarin', :variety => 'Fall Glo' },
  '3152' => { :code => '3152', :type => 'Grapefruit', :variety => 'Melogold' },
  '3160' => { :code => '3160', :type => 'Choy', :variety => 'Gai Lan / Chinese Broccoli' },
  '3162' => { :code => '3162', :type => 'Choy', :variety => 'On Choy / Water Spinach' },
  '3163' => { :code => '3163', :type => 'Choy', :variety => 'Bok Choy / Pak Choy / Shanghai' },
  '3164' => { :code => '3164', :type => 'Choy', :variety => 'Yu Choy' },
  '3165' => { :code => '3165', :type => 'Radicchio', :variety => 'Treviso' },
  '3166' => { :code => '3166', :type => 'Cabbage', :variety => 'Tuscan' },
  '3167' => { :code => '3167', :type => 'Endive / Chicory', :variety => 'Frisee' },
  '3168' => { :code => '3168', :type => 'Radicchio', :variety => 'Castlelfranco' },
  '3169' => { :code => '3169', :type => 'Lettuce', :variety => 'Catalogna' },
  '3271' => { :code => '3271', :type => 'Apple', :variety => 'Virginia Gold' },
  '3272' => { :code => '3272', :type => 'Apple', :variety => 'Sommerfeld' },
  '3273' => { :code => '3273', :type => 'Beet', :variety => 'Golden' },
  '3277' => { :code => '3277', :type => 'Broccoli', :variety => 'Baby' },
  '3278' => { :code => '3278', :type => 'Plum', :variety => 'InterSpecific' },
  '3279' => { :code => '3279', :type => 'Kiwi Fruit', :variety => 'Golden' },
  '3283' => { :code => '3283', :type => 'Apple', :variety => 'Honeycrisp' },
  '3286' => { :code => '3286', :type => 'Onion', :variety => 'Sweet, red, Italian, [flat]' },
  '3287' => { :code => '3287', :type => 'Banana', :variety => 'Hawaiian Plantain' },
  '3289' => { :code => '3289', :type => 'Melon', :variety => 'Sprite' },
  '3291' => { :code => '3291', :type => 'Apple', :variety => 'Boskoop / Belle de Boskoop, small' },
  '3292' => { :code => '3292', :type => 'Apple', :variety => 'Boskoop / Belle de Boskoop, large' },
  '3297' => { :code => '3297', :type => 'Apple', :variety => 'Scired / Pacific Queen' },
  '3303' => { :code => '3303', :type => 'Papaya / Pawpaw', :variety => 'Babaco' },
  '3304' => { :code => '3304', :type => 'Berries', :variety => 'Loganberries' },
  '3305' => { :code => '3305', :type => 'Currant', :variety => 'Black' },
  '3309' => { :code => '3309', :type => 'Orange', :variety => 'Lima' },
  '3310' => { :code => '3310', :type => 'Orange', :variety => 'Pera' },
  '3311' => { :code => '3311', :type => 'Passion Fruit', :variety => 'Curuba / Banana' },
  '3312' => { :code => '3312', :type => 'Passion Fruit', :variety => 'Granadilla Yellow / Maracuya' },
  '3320' => { :code => '3320', :type => 'Broccoli', :variety => 'Romanesco / Broccoflower / Caulibroc' },
  '3325' => { :code => '3325', :type => 'Lettuce', :variety => 'Lollo Bionda / Coral Green' },
  '3326' => { :code => '3326', :type => 'Lettuce', :variety => 'Lollo Rossa / Coral Red' },
  '3327' => { :code => '3327', :type => 'Lettuce', :variety => 'Mignonette, compact red-tinged butterhead varieties' },
  '3328' => { :code => '3328', :type => 'Lettuce', :variety => 'Mixed, small-leaf, salad [eg, Sucrine / Mesclun / Rocket / Arugula]' },
  '3332' => { :code => '3332', :type => 'Spinach', :variety => 'Baby' },
  '3336' => { :code => '3336', :type => 'Tomato', :variety => 'Cocktail / Intermediate Red / Plum / Italian / Saladette / Roma, on the vine [Truss]' },
  '3337' => { :code => '3337', :type => 'Fig', :variety => 'dried' },
  '3338' => { :code => '3338', :type => 'Herbs', :variety => 'Anise' },
  '3339' => { :code => '3339', :type => 'Apple', :variety => 'Belchard / Chantecler' },
  '3340' => { :code => '3340', :type => 'Apple', :variety => 'Bertanne / Golden Russet' },
  '3341' => { :code => '3341', :type => 'Apple', :variety => 'Charles Ross' },
  '3342' => { :code => '3342', :type => 'Apple', :variety => 'Delblush / Tentation' },
  '3343' => { :code => '3343', :type => 'Apple', :variety => 'Dessert' },
  '3346' => { :code => '3346', :type => 'Apple', :variety => 'Holstein' },
  '3347' => { :code => '3347', :type => 'Apple', :variety => 'Laxtons Fortune' },
  '3348' => { :code => '3348', :type => 'Apple', :variety => 'Lord Lambourne' },
  '3349' => { :code => '3349', :type => 'Apple', :variety => 'Michaelmas Red' },
  '3352' => { :code => '3352', :type => 'Apple', :variety => 'Reinettes and Heritage varieties' },
  '3353' => { :code => '3353', :type => 'Apple', :variety => 'St. Edmunds Pippin' },
  '3359' => { :code => '3359', :type => 'Grape', :variety => 'Chasselas' },
  '3360' => { :code => '3360', :type => 'Grape', :variety => 'Muscat de Hambourg' },
  '3363' => { :code => '3363', :type => 'Mango', :variety => 'Bowen & Kensington Pride, extra large' },
  '3364' => { :code => '3364', :type => 'Mango', :variety => 'R2E2,ArtwoEetwo, extra large' },
  '3366' => { :code => '3366', :type => 'Madro?a', :variety => '' },
  '3368' => { :code => '3368', :type => 'Melon', :variety => 'Ogen' },
  '3369' => { :code => '3369', :type => 'Nectarine', :variety => 'Nectavigne, red flesh' },
  '3370' => { :code => '3370', :type => 'Orange', :variety => 'Maltaise' },
  '3371' => { :code => '3371', :type => 'Orange', :variety => 'Salustiana' },
  '3372' => { :code => '3372', :type => 'Orange', :variety => 'Navelate / other late Navel varieties' },
  '3373' => { :code => '3373', :type => 'Orange', :variety => 'Navelina, including Newhall' },
  '3375' => { :code => '3375', :type => 'Peach', :variety => 'Peche de Vigne / Sanguine, red flesh' },
  '3376' => { :code => '3376', :type => 'Pear', :variety => 'Alexander Lucas' },
  '3377' => { :code => '3377', :type => 'Pear', :variety => 'Louise Bonne' },
  '3378' => { :code => '3378', :type => 'Pear', :variety => 'Santa Maria' },
  '3379' => { :code => '3379', :type => 'Pineapple', :variety => 'Mini' },
  '3380' => { :code => '3380', :type => 'Pineapple', :variety => 'Perola' },
  '3381' => { :code => '3381', :type => 'Soursop', :variety => '' },
  '3382' => { :code => '3382', :type => 'Apple', :variety => 'Sugar Apple' },
  '3390' => { :code => '3390', :type => 'Arracach', :variety => '' },
  '3391' => { :code => '3391', :type => 'Artichoke', :variety => 'Rouge Salambo, red' },
  '3397' => { :code => '3397', :type => 'Cabbage', :variety => 'Summer, pointed type' },
  '3398' => { :code => '3398', :type => 'Pea', :variety => 'Chick Pea / Garbanzo' },
  '3401' => { :code => '3401', :type => 'Garlic', :variety => 'One-clove types' },
  '3404' => { :code => '3404', :type => 'Mushroom', :variety => 'Cep' },
  '3405' => { :code => '3405', :type => 'Mushroom', :variety => 'Fairy Ring Champignon' },
  '3406' => { :code => '3406', :type => 'Mushroom', :variety => 'Grey Tricholoma' },
  '3407' => { :code => '3407', :type => 'Mushroom', :variety => 'Grisette' },
  '3408' => { :code => '3408', :type => 'Mushroom', :variety => 'Horn of Plenty / Black Trumpet' },
  '3409' => { :code => '3409', :type => 'Mushroom', :variety => 'Pioppino' },
  '3410' => { :code => '3410', :type => 'Mushroom', :variety => 'Saffron Milk-Cap' },
  '3411' => { :code => '3411', :type => 'Mushroom', :variety => 'Sheep Polypore' },
  '3413' => { :code => '3413', :type => 'Pepper', :variety => 'Tabasco' },
  '3419' => { :code => '3419', :type => 'Herbs', :variety => 'Borage' },
  '3421' => { :code => '3421', :type => 'Melon', :variety => 'Mini, seedless [3-7 pounds]' },
  '3422' => { :code => '3422', :type => 'Apricot', :variety => 'InterSpecific' },
  '3423' => { :code => '3423', :type => 'Tomato', :variety => 'Heirloom' },
  '3424' => { :code => '3424', :type => 'Carrot', :variety => 'Purple / Red / Beta Sweet' },
  '4033' => { :code => '4033', :type => 'LEMON', :variety => 'Lemons' },
  '4034' => { :code => '4034', :type => 'MELON', :variety => 'Honeydew' },
  '4035' => { :code => '4035', :type => 'CITRUS', :variety => 'Nectarines' },
  '4036' => { :code => '4036', :type => 'NECTARINE', :variety => 'California Nectarines' },
  '4040' => { :code => '4040', :type => 'PLUM', :variety => 'Black Plums' },
  '4041' => { :code => '4041', :type => 'PLUM', :variety => 'Plums' },
  '4042' => { :code => '4042', :type => 'PLUM', :variety => 'Large Plums' },
  '4045' => { :code => '4045', :type => 'BERRIES', :variety => 'Cherries' },
  '4048' => { :code => '4048', :type => 'MELON', :variety => 'Lime' },
  '4050' => { :code => '4050', :type => 'MELON', :variety => 'Cantelope' },
  '4051' => { :code => '4051', :type => 'MANGO', :variety => '' },
  '4053' => { :code => '4053', :type => 'LEMON', :variety => 'lemons' },
  '4054' => { :code => '4054', :type => 'Berries', :variety => 'Raspberries, red' },
  '4055' => { :code => '4055', :type => 'Tangerine / Mandarin', :variety => '' },
  '4060' => { :code => '4060', :type => 'BROCOLLI', :variety => 'Broccoli' },
  '4061' => { :code => '4061', :type => 'LETTUCE', :variety => 'Iceberg lettuce' },
  '4062' => { :code => '4062', :type => 'CUCUMBER', :variety => 'Cucumbers' },
  '4064' => { :code => '4064', :type => 'TOMATO', :variety => 'Tomatoes' },
  '4065' => { :code => '4065', :type => 'PEPPER', :variety => 'Green Peppers' },
  '4066' => { :code => '4066', :type => 'BEAN', :variety => 'Green Beans' },
  '4067' => { :code => '4067', :type => 'SQUASH', :variety => 'green squash' },
  '4068' => { :code => '4068', :type => 'ONION', :variety => 'Green Scallions (bunch)' },
  '4069' => { :code => '4069', :type => 'CABBAGE', :variety => 'Green Cabbage' },
  '4070' => { :code => '4070', :type => 'CELERY', :variety => '' },
  '4071' => { :code => '4071', :type => 'POTATO', :variety => 'Red Potatoes' },
  '4072' => { :code => '4072', :type => 'POTATO', :variety => 'Russet Potatoes' },
  '4075' => { :code => '4075', :type => 'LETTUCE', :variety => 'Red Leaf Lettuce' },
  '4076' => { :code => '4076', :type => 'LETTUCE', :variety => 'Green Leaf Lettuce' },
  '4078' => { :code => '4078', :type => 'CORN', :variety => '' },
  '4079' => { :code => '4079', :type => 'Cauliflower', :variety => '' },
  '4080' => { :code => '4080', :type => 'ASPARAGUS', :variety => '' },
  '4081' => { :code => '4081', :type => 'EGGPLANT', :variety => '' },
  '4082' => { :code => '4082', :type => 'ONION', :variety => 'Red Onions' },
  '4084' => { :code => '4084', :type => 'Artichoke', :variety => 'Artichokes' },
  '4086' => { :code => '4086', :type => 'Squash', :variety => 'Yellow Zucchini / Gold Bar / Yellow Courgette' },
  '4087' => { :code => '4087', :type => 'TOMATO', :variety => 'Plum Tomatoes' },
  '4088' => { :code => '4088', :type => 'PEPPER', :variety => 'Red peppers' },
  '4089' => { :code => '4089', :type => 'RADISH', :variety => 'Radishes (bunch)' },
  '4090' => { :code => '4090', :type => 'SPINICH', :variety => 'Spinach Bunch' },
  '4092' => { :code => '4092', :type => 'Pea', :variety => 'Chinese Snow Pea / Pea Pod / Mange Tout' },
  '4094' => { :code => '4094', :type => 'Carrot', :variety => 'Bunch' },
  '4095' => { :code => '4095', :type => 'Turnip / Rutabaga / Swede', :variety => 'Yellow' },
  '4098' => { :code => '4098', :type => 'Apple', :variety => 'Akane, small' },
  '4099' => { :code => '4099', :type => 'Apple', :variety => 'Akane, large' },
  '4101' => { :code => '4101', :type => 'Apple', :variety => 'Braeburn, small' },
  '4103' => { :code => '4103', :type => 'APPLE', :variety => 'Braeburn Apples' },
  '4105' => { :code => '4105', :type => 'Apple', :variety => 'Cox Orange Pippin' },
  '4107' => { :code => '4107', :type => 'Apple', :variety => 'Crab' },
  '4120' => { :code => '4120', :type => 'APPLE', :variety => 'Idared Apples/Fiesta' },
  '4124' => { :code => '4124', :type => 'APPLE', :variety => 'Empire Apples' },
  '4133' => { :code => '4133', :type => 'APPLE', :variety => 'Small Gala Apple' },
  '4152' => { :code => '4152', :type => 'APPLE', :variety => 'Macintosh Apples' },
  '4159' => { :code => '4159', :type => 'Onion', :variety => 'Vidalia' },
  '4161' => { :code => '4161', :type => 'Onion', :variety => 'Texas Sweet' },
  '4163' => { :code => '4163', :type => 'Onion', :variety => 'Walla Walla' },
  '4164' => { :code => '4164', :type => 'Onion', :variety => 'Maui' },
  '4165' => { :code => '4165', :type => 'Onion', :variety => 'California Sweet' },
  '4166' => { :code => '4166', :type => 'Onion', :variety => 'Other Sweet' },
  '4176' => { :code => '4176', :type => 'Apple', :variety => 'Southern Snap' },
  '4182' => { :code => '4182', :type => 'Apple', :variety => 'Sturmer Pippin' },
  '4218' => { :code => '4218', :type => 'APRICOT', :variety => 'Apricots' },
  '4220' => { :code => '4220', :type => 'Atemoya', :variety => '' },
  '4225' => { :code => '4225', :type => 'AVACADO', :variety => '' },
  '4226' => { :code => '4226', :type => 'Avocado', :variety => 'Cocktail / Seedless' },
  '4229' => { :code => '4229', :type => 'Banana', :variety => 'Burro' },
  '4230' => { :code => '4230', :type => 'Banana', :variety => 'Dominique' },
  '4231' => { :code => '4231', :type => 'Banana', :variety => 'Green' },
  '4232' => { :code => '4232', :type => 'Banana', :variety => 'Banana Leaves' },
  '4233' => { :code => '4233', :type => 'Banana', :variety => 'Manzano / Apple Banana' },
  '4234' => { :code => '4234', :type => 'Banana', :variety => 'Nino' },
  '4235' => { :code => '4235', :type => 'BANANA', :variety => 'Plantains/Macho' },
  '4236' => { :code => '4236', :type => 'Banana', :variety => 'Red' },
  '4239' => { :code => '4239', :type => 'Berries', :variety => 'Blackberries' },
  '4240' => { :code => '4240', :type => 'Berries', :variety => 'Blueberries' },
  '4241' => { :code => '4241', :type => 'Berries', :variety => 'Boysenberries' },
  '4242' => { :code => '4242', :type => 'Berries', :variety => 'Cranberries' },
  '4243' => { :code => '4243', :type => 'Berries', :variety => 'Gooseberries' },
  '4244' => { :code => '4244', :type => 'Berries', :variety => 'Black Raspberries' },
  '4245' => { :code => '4245', :type => 'Berries', :variety => 'Golden Raspberries' },
  '4248' => { :code => '4248', :type => 'Berries', :variety => 'Quart' },
  '4251' => { :code => '4251', :type => 'Berries', :variety => 'Long-stemmed' },
  '4254' => { :code => '4254', :type => 'Breadfruit', :variety => '' },
  '4255' => { :code => '4255', :type => 'Cactus', :variety => 'Cactus Pear / Prickly Pear' },
  '4256' => { :code => '4256', :type => 'Carambola / Starfruit', :variety => '' },
  '4257' => { :code => '4257', :type => 'Cherimoya', :variety => '' },
  '4258' => { :code => '4258', :type => 'Cherry', :variety => 'Golden / Ranier / White' },
  '4260' => { :code => '4260', :type => 'Coconut', :variety => 'In Husk / Waternut' },
  '4261' => { :code => '4261', :type => 'Coconut', :variety => 'Husked' },
  '4265' => { :code => '4265', :type => 'Feijoa', :variety => '' },
  '4266' => { :code => '4266', :type => 'Fig', :variety => 'Black' },
  '4267' => { :code => '4267', :type => 'Fig', :variety => 'Brown' },
  '4268' => { :code => '4268', :type => 'Fig', :variety => 'White / Green' },
  '4271' => { :code => '4271', :type => 'Grape', :variety => 'Champagne' },
  '4272' => { :code => '4272', :type => 'Grape', :variety => 'Concord' },
  '4299' => { :code => '4299', :type => 'Guava', :variety => '' },
  '4300' => { :code => '4300', :type => 'Homli Fruit', :variety => '' },
  '4302' => { :code => '4302', :type => 'Melon', :variety => 'Horned Melon / Kiwano' },
  '4303' => { :code => '4303', :type => 'Kumquat', :variety => '' },
  '4305' => { :code => '4305', :type => 'Lime', :variety => 'Key, including Mexican / West Indian' },
  '4307' => { :code => '4307', :type => 'Longan', :variety => '' },
  '4308' => { :code => '4308', :type => 'Loquat', :variety => '' },
  '4309' => { :code => '4309', :type => 'Lychee', :variety => '' },
  '4310' => { :code => '4310', :type => 'Mamey', :variety => '' },
  '4311' => { :code => '4311', :type => 'Mango', :variety => 'Green' },
  '4312' => { :code => '4312', :type => 'Mango', :variety => 'Yellow' },
  '4317' => { :code => '4317', :type => 'Melon', :variety => 'Canary / Yellow Honeydew' },
  '4320' => { :code => '4320', :type => 'Melon', :variety => 'Casaba' },
  '4321' => { :code => '4321', :type => 'Melon', :variety => 'Cinnabar' },
  '4322' => { :code => '4322', :type => 'Melon', :variety => 'Crenshaw' },
  '4324' => { :code => '4324', :type => 'Melon', :variety => 'French Afternoon' },
  '4325' => { :code => '4325', :type => 'Melon', :variety => 'French Breakfast' },
  '4326' => { :code => '4326', :type => 'Melon', :variety => 'Galia' },
  '4327' => { :code => '4327', :type => 'Melon', :variety => 'Orange Flesh / Cantaline' },
  '4328' => { :code => '4328', :type => 'Limequat', :variety => '' },
  '4329' => { :code => '4329', :type => 'MELON', :variety => 'Honeydew Melon' },
  '4330' => { :code => '4330', :type => 'Melon', :variety => 'Mayan' },
  '4331' => { :code => '4331', :type => 'Melon', :variety => 'Mickey Lee / Sugarbaby' },
  '4332' => { :code => '4332', :type => 'Melon', :variety => 'Muskmelon' },
  '4333' => { :code => '4333', :type => 'Melon', :variety => 'Pepino' },
  '4334' => { :code => '4334', :type => 'Melon', :variety => 'Persian' },
  '4335' => { :code => '4335', :type => 'Melon', :variety => 'Prince' },
  '4336' => { :code => '4336', :type => 'Melon', :variety => 'Santa Claus' },
  '4337' => { :code => '4337', :type => 'Melon', :variety => 'Saticoy' },
  '4338' => { :code => '4338', :type => 'Melon', :variety => 'Sharlin' },
  '4339' => { :code => '4339', :type => 'Melon', :variety => 'Spanish / Tendral' },
  '4381' => { :code => '4381', :type => 'Orange', :variety => 'Blood' },
  '4382' => { :code => '4382', :type => 'Orange', :variety => 'Juice' },
  '4383' => { :code => '4383', :type => 'Orange', :variety => 'Tangelo Minneola' },
  '4395' => { :code => '4395', :type => 'Papaya / Pawpaw', :variety => 'Cooking / Mexican' },
  '4397' => { :code => '4397', :type => 'Passion Fruit', :variety => 'Purple' },
  '4399' => { :code => '4399', :type => 'Peach', :variety => 'Indian' },
  '4401' => { :code => '4401', :type => 'PEACH', :variety => 'White Peaches' },
  '4402' => { :code => '4402', :type => 'PEACH', :variety => 'Peaches' },
  '4409' => { :code => '4409', :type => 'PEAR', :variety => 'Bartlett Pears' },
  '4410' => { :code => '4410', :type => 'Pear', :variety => 'Bartlett Red / Red Sensation' },
  '4412' => { :code => '4412', :type => 'PEAR', :variety => 'Bosc Pears' },
  '4415' => { :code => '4415', :type => 'Pear', :variety => 'Red' },
  '4418' => { :code => '4418', :type => 'Pear', :variety => 'Forelle / Corella' },
  '4419' => { :code => '4419', :type => 'Pear', :variety => 'French' },
  '4420' => { :code => '4420', :type => 'Pear', :variety => 'King Royal' },
  '4422' => { :code => '4422', :type => 'Pear', :variety => 'Seckel' },
  '4423' => { :code => '4423', :type => 'Pear', :variety => 'Tree Ripened' },
  '4424' => { :code => '4424', :type => 'Pear', :variety => 'Winter Nelis / Honey' },
  '4427' => { :code => '4427', :type => 'Persimmon', :variety => 'Regular / American Persimmon' },
  '4428' => { :code => '4428', :type => 'Persimmon', :variety => 'Japanese / Sharonfruit [Kaki]' },
  '4436' => { :code => '4436', :type => 'Plum', :variety => 'Italian Prune / Sugar' },
  '4447' => { :code => '4447', :type => 'Quince', :variety => '' },
  '4448' => { :code => '4448', :type => 'Tamarindo', :variety => '' },
  '4449' => { :code => '4449', :type => 'Tangerine / Mandarin', :variety => 'Sunburst' },
  '4451' => { :code => '4451', :type => 'Tangerine / Mandarin', :variety => 'Dancy' },
  '4452' => { :code => '4452', :type => 'Tangerine / Mandarin', :variety => 'Fairchild' },
  '4454' => { :code => '4454', :type => 'Tangerine / Mandarin', :variety => 'Kinnow' },
  '4455' => { :code => '4455', :type => 'Tangerine / Mandarin', :variety => 'Mandarin / Royal' },
  '4470' => { :code => '4470', :type => 'Salad Bar', :variety => '' },
  '4497' => { :code => '4497', :type => 'Grape', :variety => 'Sugarone / Autumn, seedless' },
  '4499' => { :code => '4499', :type => 'Grape', :variety => 'Crimson / Majestic' },
  '4514' => { :code => '4514', :type => 'Alfalfa Sprouts', :variety => '' },
  '4515' => { :code => '4515', :type => 'ANISE', :variety => 'Fennel / Florence / Sweet Fennel / Fennel Bulb' },
  '4519' => { :code => '4519', :type => 'Artichoke', :variety => 'Baby / Cocktail' },
  '4524' => { :code => '4524', :type => 'Asparagus', :variety => 'Tips' },
  '4527' => { :code => '4527', :type => 'Bean', :variety => 'Chinese Long / Snake' },
  '4528' => { :code => '4528', :type => 'Bean', :variety => 'Fava / Broad' },
  '4529' => { :code => '4529', :type => 'Bean', :variety => 'Lima' },
  '4530' => { :code => '4530', :type => 'Bean', :variety => 'Pole / Runner / Stick' },
  '4531' => { :code => '4531', :type => 'Bean', :variety => 'Purple Hull' },
  '4532' => { :code => '4532', :type => 'Bean', :variety => 'Shell' },
  '4533' => { :code => '4533', :type => 'Bean', :variety => 'Wax / Yellow' },
  '4534' => { :code => '4534', :type => 'Bean', :variety => 'Winged' },
  '4536' => { :code => '4536', :type => 'Bean', :variety => 'Bean Sprouts / Mung Bean Sprouts' },
  '4537' => { :code => '4537', :type => 'Beet', :variety => 'Baby Golden' },
  '4538' => { :code => '4538', :type => 'Beet', :variety => 'Baby Red' },
  '4539' => { :code => '4539', :type => 'Beet', :variety => 'Bunch' },
  '4540' => { :code => '4540', :type => 'Beet', :variety => 'Loose' },
  '4542' => { :code => '4542', :type => 'Beet', :variety => 'Beet Greens' },
  '4543' => { :code => '4543', :type => 'ENDIVE', :variety => 'Belgium endive' },
  '4545' => { :code => '4545', :type => 'CHOY', :variety => 'Bok Choy' },
  '4546' => { :code => '4546', :type => 'Potato', :variety => 'Boniato / Sweet Potato' },
  '4547' => { :code => '4547', :type => 'Broccoli', :variety => 'Broccoli Rabe / Italian Rapini / Chinese Broccoli / Gai Lan' },
  '4548' => { :code => '4548', :type => 'BROCOLLI', :variety => 'Broccoli Crowns' },
  '4550' => { :code => '4550', :type => 'Brussels Sprout', :variety => '' },
  '4552' => { :code => '4552', :type => 'Cabbage', :variety => 'Chinese / Napa / Wong Bok' },
  '4553' => { :code => '4553', :type => 'Pear', :variety => 'Taylors Gold' },
  '4554' => { :code => '4554', :type => 'Cabbage', :variety => 'Red' },
  '4558' => { :code => '4558', :type => 'Cactus', :variety => 'Cactus Leaves / Nopales / Cactus Pads' },
  '4559' => { :code => '4559', :type => 'Cardoon / Cardoni', :variety => '' },
  '4560' => { :code => '4560', :type => 'Carrot', :variety => 'Baby' },
  '4561' => { :code => '4561', :type => 'Carrot', :variety => 'French' },
  '4562' => { :code => '4562', :type => 'Carrot', :variety => 'Loose' },
  '4563' => { :code => '4563', :type => 'Carrot', :variety => 'Carrot Sticks' },
  '4566' => { :code => '4566', :type => 'Cauliflower', :variety => 'Florettes' },
  '4567' => { :code => '4567', :type => 'Cauliflower', :variety => 'Green' },
  '4568' => { :code => '4568', :type => 'Cauliflower', :variety => 'Purple' },
  '4573' => { :code => '4573', :type => 'Cauliflower', :variety => 'Baby' },
  '4575' => { :code => '4575', :type => 'Celery', :variety => 'Hearts' },
  '4576' => { :code => '4576', :type => 'CELERY', :variety => 'Celery Sticks' },
  '4592' => { :code => '4592', :type => 'Cucumber', :variety => 'Armenian' },
  '4593' => { :code => '4593', :type => 'Cucumber', :variety => 'English / Hot House / Long Seedless / Telegraph / Continental' },
  '4594' => { :code => '4594', :type => 'Cucumber', :variety => 'Japanese / White' },
  '4595' => { :code => '4595', :type => 'Cucumber', :variety => 'Lemon' },
  '4596' => { :code => '4596', :type => 'Cucumber', :variety => 'Pickling / Gherkin' },
  '4598' => { :code => '4598', :type => 'RADISH', :variety => 'Daikon / Radish' },
  '4599' => { :code => '4599', :type => 'KUMQUAT', :variety => '' },
  '4601' => { :code => '4601', :type => 'Eggplant', :variety => 'Japanese' },
  '4602' => { :code => '4602', :type => 'Eggplant', :variety => 'White' },
  '4604' => { :code => '4604', :type => 'ENDIVE', :variety => 'Endive / Chicory' },
  '4606' => { :code => '4606', :type => 'Fiddlehead Ferns', :variety => '' },
  '4608' => { :code => '4608', :type => 'GARLIC', :variety => 'Loose Garlic' },
  '4609' => { :code => '4609', :type => 'Garlic', :variety => 'Elephant' },
  '4612' => { :code => '4612', :type => 'GINGER', :variety => 'Ginger Root' },
  '4614' => { :code => '4614', :type => 'Greens', :variety => 'Collards' },
  '4615' => { :code => '4615', :type => 'Greens', :variety => 'Dandelion' },
  '4616' => { :code => '4616', :type => 'Greens', :variety => 'Mustard' },
  '4617' => { :code => '4617', :type => 'Greens', :variety => 'Polk Greens' },
  '4618' => { :code => '4618', :type => 'Greens', :variety => 'Texas Mustard' },
  '4619' => { :code => '4619', :type => 'Greens', :variety => 'Turnip' },
  '4625' => { :code => '4625', :type => 'Horseradish Root', :variety => '' },
  '4626' => { :code => '4626', :type => 'Jicama / Yam Bean', :variety => '' },
  '4631' => { :code => '4631', :type => 'Lettuce', :variety => 'Bibb / Flat / Round' },
  '4632' => { :code => '4632', :type => 'LETTUCE', :variety => 'Boston Lettuce' },
  '4633' => { :code => '4633', :type => 'Lettuce', :variety => 'Hydroponic' },
  '4636' => { :code => '4636', :type => 'GRAPES', :variety => 'Red Globe Grapes' },
  '4638' => { :code => '4638', :type => 'Grape', :variety => 'Fantasy / Marroo' },
  '4639' => { :code => '4639', :type => 'Lettuce', :variety => 'Mache' },
  '4640' => { :code => '4640', :type => 'LETTUCE', :variety => 'Romaine Lettuce' },
  '4644' => { :code => '4644', :type => 'Malanga', :variety => '' },
  '4645' => { :code => '4645', :type => 'MUSHROOM', :variety => 'Mushrooms' },
  '4646' => { :code => '4646', :type => 'Mushroom', :variety => 'Black Forest' },
  '4647' => { :code => '4647', :type => 'Mushroom', :variety => 'Chanterelle' },
  '4648' => { :code => '4648', :type => 'Mushroom', :variety => 'Cremini / Brown / Swiss Brown' },
  '4649' => { :code => '4649', :type => 'Mushroom', :variety => 'Oyster' },
  '4650' => { :code => '4650', :type => 'MUSHROOM', :variety => 'Portabello Mushrooms' },
  '4651' => { :code => '4651', :type => 'Mushroom', :variety => 'Shiitake' },
  '4652' => { :code => '4652', :type => 'Mushroom', :variety => 'Wood Ear' },
  '4655' => { :code => '4655', :type => 'Okra', :variety => 'Regular, green' },
  '4656' => { :code => '4656', :type => 'Okra', :variety => 'Chinese' },
  '4657' => { :code => '4657', :type => 'Okra', :variety => 'Red' },
  '4658' => { :code => '4658', :type => 'Onion', :variety => 'Boiling' },
  '4659' => { :code => '4659', :type => 'Onion', :variety => 'Bulb' },
  '4660' => { :code => '4660', :type => 'Onion', :variety => 'Pearl' },
  '4661' => { :code => '4661', :type => 'Onion', :variety => 'Pickling, white' },
  '4662' => { :code => '4662', :type => 'Onion', :variety => 'Shallots' },
  '4663' => { :code => '4663', :type => 'ONION', :variety => 'White Onions' },
  '4664' => { :code => '4664', :type => 'TOMATO', :variety => 'Tomatoes on a Vine' },
  '4665' => { :code => '4665', :type => 'ONION', :variety => 'Yellow Cooking Onions' },
  '4671' => { :code => '4671', :type => 'Herbs', :variety => 'Parsley Root / Hamburg Parsley' },
  '4672' => { :code => '4672', :type => 'Parsnip', :variety => 'Parsnips' },
  '4673' => { :code => '4673', :type => 'Pea', :variety => 'Blackeyed' },
  '4674' => { :code => '4674', :type => 'Pea', :variety => 'Green' },
  '4675' => { :code => '4675', :type => 'Pea', :variety => 'Sugar Snap' },
  '4677' => { :code => '4677', :type => 'Pepper', :variety => 'Anaheim, green, red' },
  '4678' => { :code => '4678', :type => 'Pepper', :variety => 'Banana, yellow, long' },
  '4681' => { :code => '4681', :type => 'PEPPER', :variety => 'Green Peppers' },
  '4687' => { :code => '4687', :type => 'PEPPER', :variety => 'Cubenelle Peppers' },
  '4688' => { :code => '4688', :type => 'PEPPER', :variety => 'Red Sweet Peppers' },
  '4690' => { :code => '4690', :type => 'Pepper', :variety => 'Hot / Hungarian Hot' },
  '4691' => { :code => '4691', :type => 'Pepper', :variety => 'Hot Mixed' },
  '4692' => { :code => '4692', :type => 'Pepper', :variety => 'Hungarian Wax' },
  '4693' => { :code => '4693', :type => 'PEPPER', :variety => 'Jalapeno Peppers' },
  '4695' => { :code => '4695', :type => 'Pepper', :variety => 'Japanese, red' },
  '4698' => { :code => '4698', :type => 'Pepper', :variety => 'Morita Chili' },
  '4699' => { :code => '4699', :type => 'Pepper', :variety => 'Negro' },
  '4700' => { :code => '4700', :type => 'Pepper', :variety => 'New Mexico' },
  '4704' => { :code => '4704', :type => 'Pepper', :variety => 'Pinole' },
  '4705' => { :code => '4705', :type => 'Pepper', :variety => 'Poblano' },
  '4706' => { :code => '4706', :type => 'Pepper', :variety => 'Red Cheese' },
  '4707' => { :code => '4707', :type => 'Pepper', :variety => 'Red Finger' },
  '4708' => { :code => '4708', :type => 'Pepper', :variety => 'Red Pimiento / Red, sweet, long' },
  '4709' => { :code => '4709', :type => 'Pepper', :variety => 'Serrano' },
  '4726' => { :code => '4726', :type => 'Potato', :variety => 'Long, white' },
  '4727' => { :code => '4727', :type => 'POTATO', :variety => 'Yukon Potato' },
  '4735' => { :code => '4735', :type => 'Pumpkin', :variety => 'Regular' },
  '4738' => { :code => '4738', :type => 'RADICCHIO', :variety => '' },
  '4739' => { :code => '4739', :type => 'Radish', :variety => 'Black' },
  '4741' => { :code => '4741', :type => 'Radish', :variety => 'Italian, red' },
  '4742' => { :code => '4742', :type => 'Radish', :variety => 'Red' },
  '4743' => { :code => '4743', :type => 'Radish', :variety => 'White / Icicle' },
  '4747' => { :code => '4747', :type => 'RUTABAGA', :variety => '' },
  '4753' => { :code => '4753', :type => 'Squash', :variety => 'Australian Blue' },
  '4755' => { :code => '4755', :type => 'Squash', :variety => 'Summer, green, baby' },
  '4757' => { :code => '4757', :type => 'Squash', :variety => 'Banana' },
  '4758' => { :code => '4758', :type => 'Squash', :variety => 'Buttercup' },
  '4759' => { :code => '4759', :type => 'Squash', :variety => 'Butternut' },
  '4760' => { :code => '4760', :type => 'Squash', :variety => 'Calabaza' },
  '4761' => { :code => '4761', :type => 'Squash', :variety => 'Chayote / Choko' },
  '4763' => { :code => '4763', :type => 'Squash', :variety => 'Delicata / Sweet Potato Squash' },
  '4764' => { :code => '4764', :type => 'Squash', :variety => 'Sweet Dumpling' },
  '4765' => { :code => '4765', :type => 'Squash', :variety => 'Gem' },
  '4766' => { :code => '4766', :type => 'Squash', :variety => 'Golden Delicious' },
  '4767' => { :code => '4767', :type => 'Squash', :variety => 'Golden Nugget' },
  '4768' => { :code => '4768', :type => 'Squash', :variety => 'Hubbard' },
  '4769' => { :code => '4769', :type => 'Squash', :variety => 'Kabocha' },
  '4771' => { :code => '4771', :type => 'AVACADO', :variety => '' },
  '4773' => { :code => '4773', :type => 'Squash', :variety => 'Patty Pan / Summer' },
  '4774' => { :code => '4774', :type => 'Squash', :variety => 'Red Kuri' },
  '4776' => { :code => '4776', :type => 'Squash', :variety => 'Spaghetti / Vegetable Spaghetti' },
  '4777' => { :code => '4777', :type => 'Squash', :variety => 'Sunburst, yellow' },
  '4779' => { :code => '4779', :type => 'Squash', :variety => 'Sweet Mama' },
  '4780' => { :code => '4780', :type => 'Squash', :variety => 'Turban' },
  '4781' => { :code => '4781', :type => 'Squash', :variety => 'White' },
  '4782' => { :code => '4782', :type => 'PEPPER', :variety => 'Yellow Straigtneck Peppers' },
  '4783' => { :code => '4783', :type => 'Squash', :variety => 'Bitter Melon / Bitter Gourd / Foo Qua' },
  '4784' => { :code => '4784', :type => 'Squash', :variety => 'Yellow Crookneck' },
  '4790' => { :code => '4790', :type => 'Sugar Cane', :variety => '' },
  '4791' => { :code => '4791', :type => 'Artichoke', :variety => 'Sunchokes / Jerusalem Artichokes' },
  '4792' => { :code => '4792', :type => 'Tamarillo', :variety => 'Golden' },
  '4793' => { :code => '4793', :type => 'Tamarillo', :variety => 'Red' },
  '4799' => { :code => '4799', :type => 'TOMATO', :variety => '' },
  '4800' => { :code => '4800', :type => 'Tomato', :variety => 'Native / Home Grown' },
  '4801' => { :code => '4801', :type => 'Tomato', :variety => 'Tomatillos / Husk Tomatoes' },
  '4802' => { :code => '4802', :type => 'Tomato', :variety => 'dried' },
  '4809' => { :code => '4809', :type => 'Turnip / Rutabaga / Swede', :variety => 'Baby' },
  '4810' => { :code => '4810', :type => 'Turnip / Rutabaga / Swede', :variety => 'Bunch / Banded' },
  '4811' => { :code => '4811', :type => 'Turnip / Rutabaga / Swede', :variety => 'Purple Top' },
  '4812' => { :code => '4812', :type => 'Turnip / Rutabaga / Swede', :variety => 'White' },
  '4814' => { :code => '4814', :type => 'Waterchestnuts', :variety => '' },
  '4815' => { :code => '4815', :type => 'Herbs', :variety => 'Watercress' },
  '4816' => { :code => '4816', :type => 'POTATO', :variety => 'Yams' },
  '4819' => { :code => '4819', :type => 'Yucca Root', :variety => '' },
  '4860' => { :code => '4860', :type => 'Apple', :variety => 'dried apple slices' },
  '4861' => { :code => '4861', :type => 'Apricot', :variety => 'dried' },
  '4862' => { :code => '4862', :type => 'Date', :variety => 'dried' },
  '4864' => { :code => '4864', :type => 'Pineapple', :variety => 'dried' },
  '4884' => { :code => '4884', :type => 'Greens', :variety => 'Arugula / Rocket' },
  '4888' => { :code => '4888', :type => 'Herbs', :variety => 'Chives' },
  '4889' => { :code => '4889', :type => 'HERBS', :variety => 'Cilantro / Coriander / Chinese Parsley' },
  '4890' => { :code => '4890', :type => 'Pear', :variety => 'Chinese Yali' },
  '4891' => { :code => '4891', :type => 'HERBS', :variety => 'Dill' },
  '4892' => { :code => '4892', :type => 'Herbs', :variety => 'Baby Dill' },
  '4893' => { :code => '4893', :type => 'Herbs', :variety => 'Pickling Dill' },
  '4894' => { :code => '4894', :type => 'Herbs', :variety => 'Lemon Grass' },
  '4895' => { :code => '4895', :type => 'Herbs', :variety => 'Marjoram' },
  '4896' => { :code => '4896', :type => 'Herbs', :variety => 'Mint' },
  '4897' => { :code => '4897', :type => 'Herbs', :variety => 'Oregano' },
  '4898' => { :code => '4898', :type => 'Herbs', :variety => 'Oyster Plant / Salsify' },
  '4900' => { :code => '4900', :type => 'HERBS', :variety => 'Parsley' },
  '4901' => { :code => '4901', :type => 'HERBS', :variety => 'Italian Parsley' },
  '4903' => { :code => '4903', :type => 'Herbs', :variety => 'Rosemary' },
  '4904' => { :code => '4904', :type => 'Herbs', :variety => 'Sage' },
  '4905' => { :code => '4905', :type => 'Herbs', :variety => 'Sorrel' },
  '4906' => { :code => '4906', :type => 'Herbs', :variety => 'Tarragon' },
  '4907' => { :code => '4907', :type => 'Herbs', :variety => 'Thyme' },
  '4908' => { :code => '4908', :type => 'Herbs', :variety => 'Vanilla Bean' },
  '4924' => { :code => '4924', :type => 'Nuts', :variety => 'Almonds' },
  '4926' => { :code => '4926', :type => 'Nuts', :variety => 'Brazil nuts' },
  '4927' => { :code => '4927', :type => 'Nuts', :variety => 'Chestnuts' },
  '4928' => { :code => '4928', :type => 'Nuts', :variety => 'Filberts / Cobnut / Hazelnut' },
  '4929' => { :code => '4929', :type => 'Nuts', :variety => 'Mixed' },
  '4936' => { :code => '4936', :type => 'Nuts', :variety => 'Pecans' },
  '4938' => { :code => '4938', :type => 'Nuts', :variety => 'Pine Nuts / Pignoli' },
  '4942' => { :code => '4942', :type => 'Nuts', :variety => 'Sunflower Seeds' },
  '4948' => { :code => '4948', :type => 'LIMES', :variety => '' },
  '33543' => { :code => '33543', :type => 'Avocado', :variety => 'Ripe, ready-to-eat' },
  '33653' => { :code => '33653', :type => 'Mango', :variety => 'Ripe, ready-to-eat' },
  '33673' => { :code => '33673', :type => 'Melon', :variety => 'Glasshouse, netted varieties' },
  '34173' => { :code => '34173', :type => 'Spinach', :variety => 'New Zealand' },
  '42461' => { :code => '42461', :type => 'Berries', :variety => 'Pint' },
  '46341' => { :code => '46341', :type => 'Lettuce', :variety => 'Iceberg' },
  '47251' => { :code => '47251', :type => 'Potato', :variety => 'Russet' }
}
